
#ifdef KEYBOARD_CENTRAL
#define CENTRAL_COLS 6

#endif

#define TAPPING_TERM 200
#define MOUSE_MOVE_INTERVAL 50
#define MOUSE_MOVE_DISTANCE 20
#define WHEEL_MOVE_DISTANCE 2
#define TAPPING_TERM_FORCE_HOLD

#define KEYBOARD_POWER_LED 13
